# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "yarn"  
    directory: "/"  
    schedule:
      interval: "weekly"  
    open-pull-requests-limit: 5  #I've included an optional limit of 5 open pull requests at any given time from Dependabot to avoid overwhelming your project with too many update PRs.

